[package]
name = "dokploy-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "dokploy"
path = "src/main.rs"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
directories.workspace = true
dokploy-core.workspace = true
dokploy-engine.workspace = true
dokploy-model.workspace = true
dokploy-sdk.workspace = true
dokploy-spec.workspace = true
dokploy-state.workspace = true
getrandom.workspace = true
hmac.workspace = true
inquire.workspace = true
keyring.workspace = true
miette.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
toml_edit.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
zeroize.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[dev-dependencies]
dokploy-sim.workspace = true
semver.workspace = true
