[graph]
all-features = true

[advisories]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0",
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["Zlib"], crate = "foldhash@0.1.5" },
    { allow = ["ISC"], crate = "is_ci@1.2.0" },
    { allow = ["MPL-2.0"], crate = "option-ext@0.2.0" },
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "simplest-path"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
