[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
license = "Apache-2.0"
repository = "https://github.com/bernard-ng/dokploy-iac"
publish = false

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
syn = { version = "2.0", features = ["full"] }
tempfile = "3.23"
thiserror = "2.0"
dokploy-spec.workspace = true
