use std::{
    fs,
    path::Path,
    sync::{Arc, Mutex},
};

use serde_json::Value;
use tempfile::TempDir;
use xtask::{CodeGenerator, CodegenError, CodegenMode, CodegenPaths, GeneratorOutput, run_codegen};

const GENERATED_HEADER: &str = "// @generated by `cargo xtask codegen`; DO NOT EDIT.\n";

struct FixtureGenerator {
    operations: usize,
}

impl CodeGenerator for FixtureGenerator {
    fn version(&self) -> Result<String, std::io::Error> {
        Ok("oas3-gen 0.28.0".to_owned())
    }

    fn generate(&self, source: &Path, output: &Path) -> Result<GeneratorOutput, std::io::Error> {
        assert!(source.ends_with("dokploy.json"));
        fs::create_dir_all(output)?;
        fs::write(output.join("mod.rs"), "pub mod generated_fixture;\n")?;
        fs::write(output.join("types.rs"), "pub struct Fixture;\n")?;

        let methods = (0..self.operations)
            .map(|index| format!("    /// * Path: `GET /fixture.{index}`\n    pub async fn operation_{index}() {{}}\n"))
            .collect::<String>();
        fs::write(output.join("client.rs"), methods)?;

        Ok(GeneratorOutput::default())
    }
}

#[test]
fn codegen_writes_a_nonempty_generated_snapshot_with_do_not_edit_headers() {
    let fixture = CodegenFixture::new(1);

    let report = run_codegen(
        &FixtureGenerator { operations: 1 },
        &fixture.paths,
        CodegenMode::Write,
    )
    .expect("generation should succeed");

    assert_eq!(report.operation_count, 1);
    assert_eq!(report.file_count, 4);
    assert_eq!(report.normalized_security_references, 1);

    for file_name in ["client.rs", "metadata.rs", "mod.rs", "types.rs"] {
        let contents = fs::read_to_string(fixture.paths.committed_output.join(file_name))
            .expect("generated file should be written");
        assert!(contents.starts_with(GENERATED_HEADER));
    }
}

#[test]
fn codegen_derives_endpoint_metadata_from_the_openapi_contract() {
    let fixture = CodegenFixture::new(1);

    let report = run_codegen(
        &FixtureGenerator { operations: 1 },
        &fixture.paths,
        CodegenMode::Write,
    )
    .expect("generation should succeed");

    let metadata = fs::read_to_string(fixture.paths.committed_output.join("metadata.rs"))
        .expect("endpoint metadata should be generated");
    assert_eq!(report.file_count, 4);
    assert!(metadata.contains("pub const FIXTURE_0: Endpoint"));
    assert!(metadata.contains("EndpointMethod::Get"));
    assert!(metadata.contains(r#"Endpoint::new("fixture-0", "fixture.0""#));
    assert!(metadata.contains(r#""fixture.0" => Some(FIXTURE_0)"#));
}

#[test]
fn codegen_rejects_an_empty_generated_operation_set_without_replacing_the_snapshot() {
    let fixture = CodegenFixture::new(1);
    fs::create_dir_all(&fixture.paths.committed_output).expect("output directory should exist");
    let existing = fixture.paths.committed_output.join("client.rs");
    fs::write(&existing, "existing snapshot\n").expect("existing snapshot should be written");

    let error = run_codegen(
        &FixtureGenerator { operations: 0 },
        &fixture.paths,
        CodegenMode::Write,
    )
    .expect_err("empty generated output must fail");

    assert!(matches!(
        error,
        CodegenError::EmptyGeneratedOperations { expected: 1 }
    ));
    assert_eq!(
        fs::read_to_string(existing).expect("existing snapshot should remain readable"),
        "existing snapshot\n"
    );
}

#[test]
fn codegen_rejects_a_partial_generated_operation_set() {
    let fixture = CodegenFixture::new(2);

    let error = run_codegen(
        &FixtureGenerator { operations: 1 },
        &fixture.paths,
        CodegenMode::Write,
    )
    .expect_err("partial generated output must fail");

    assert!(matches!(
        error,
        CodegenError::OperationCountMismatch {
            expected: 2,
            actual: 1
        }
    ));
    assert!(!fixture.paths.committed_output.exists());
}

#[test]
fn codegen_check_reports_drift_without_modifying_the_snapshot() {
    let fixture = CodegenFixture::new(1);
    let generator = FixtureGenerator { operations: 1 };
    run_codegen(&generator, &fixture.paths, CodegenMode::Write)
        .expect("initial snapshot should be written");
    let drifted = fixture.paths.committed_output.join("metadata.rs");
    fs::write(&drifted, "manual edit\n").expect("snapshot should be modified for the fixture");

    let error = run_codegen(&generator, &fixture.paths, CodegenMode::Check)
        .expect_err("drifted generated output must fail the check");

    assert!(matches!(error, CodegenError::Drift(paths) if paths == vec![drifted.clone()]));
    assert_eq!(
        fs::read_to_string(drifted).expect("drifted file should remain readable"),
        "manual edit\n"
    );
}

#[test]
fn codegen_check_accepts_an_unchanged_snapshot() {
    let fixture = CodegenFixture::new(1);
    let generator = FixtureGenerator { operations: 1 };
    run_codegen(&generator, &fixture.paths, CodegenMode::Write)
        .expect("initial snapshot should be written");

    let report = run_codegen(&generator, &fixture.paths, CodegenMode::Check)
        .expect("unchanged generated output should pass the check");

    assert_eq!(report.operation_count, 1);
}

#[test]
fn codegen_rejects_the_wrong_generator_version_before_writing_output() {
    let fixture = CodegenFixture::new(1);

    let error = run_codegen(&WrongVersionGenerator, &fixture.paths, CodegenMode::Write)
        .expect_err("an unpinned generator must fail");

    assert!(matches!(
        error,
        CodegenError::GeneratorVersion { expected, actual }
            if expected == "oas3-gen 0.28.0" && actual == "oas3-gen 0.29.0"
    ));
    assert!(!fixture.paths.committed_output.exists());
}

#[test]
fn codegen_passes_the_vendored_contract_to_the_generator_without_rewriting_it() {
    let fixture = CodegenFixture::new(1);
    let original = fs::read(&fixture.paths.source).expect("fixture contract should be readable");

    run_codegen(
        &FixtureGenerator { operations: 1 },
        &fixture.paths,
        CodegenMode::Write,
    )
    .expect("generation should succeed");

    assert_eq!(
        fs::read(&fixture.paths.source).expect("fixture contract should remain readable"),
        original
    );
}

#[test]
fn codegen_normalizes_all_604_auth_references_without_changing_response_contracts() {
    let directory = tempfile::tempdir().expect("temporary directory should exist");
    let repository_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask should be below the repository root");
    let source = repository_root.join("openapi/dokploy.json");
    let original_bytes = fs::read(&source).expect("vendored contract should be readable");
    let original: Value =
        serde_json::from_slice(&original_bytes).expect("vendored contract should be valid JSON");
    let original_responses = operation_responses(&original);
    let observations = Arc::new(Mutex::new(None));
    let generator = InspectingGenerator {
        observations: Arc::clone(&observations),
    };
    let paths = CodegenPaths {
        source: source.clone(),
        committed_output: directory.path().join("generated"),
        scratch_parent: directory.path().join("scratch"),
        expected_warning_count: 0,
    };

    let report = run_codegen(&generator, &paths, CodegenMode::Write)
        .expect("full contract generation should succeed");

    let observations = observations
        .lock()
        .expect("observations lock should be available")
        .take()
        .expect("generator should inspect the normalized contract");
    assert_eq!(report.operation_count, 604);
    assert_eq!(report.normalized_security_references, 604);
    let generated_metadata = fs::read_to_string(paths.committed_output.join("metadata.rs"))
        .expect("full endpoint metadata should be generated");
    assert_eq!(generated_metadata.matches("pub const ").count(), 604);
    assert_eq!(observations.operation_count, 604);
    assert_eq!(observations.api_key_references, 604);
    assert_eq!(observations.authorization_references, 0);
    assert_eq!(observations.responses, original_responses);
    assert_eq!(
        fs::read(source).expect("vendored contract should remain readable"),
        original_bytes
    );
}

struct WrongVersionGenerator;

impl CodeGenerator for WrongVersionGenerator {
    fn version(&self) -> Result<String, std::io::Error> {
        Ok("oas3-gen 0.29.0".to_owned())
    }

    fn generate(&self, _source: &Path, _output: &Path) -> Result<GeneratorOutput, std::io::Error> {
        panic!("generation must not run with an unpinned version");
    }
}

struct InspectingGenerator {
    observations: Arc<Mutex<Option<ContractObservations>>>,
}

impl CodeGenerator for InspectingGenerator {
    fn version(&self) -> Result<String, std::io::Error> {
        Ok("oas3-gen 0.28.0".to_owned())
    }

    fn generate(&self, source: &Path, output: &Path) -> Result<GeneratorOutput, std::io::Error> {
        let normalized: Value = serde_json::from_slice(&fs::read(source)?)
            .map_err(|error| std::io::Error::other(error.to_string()))?;
        let operation_count = operation_count(&normalized);
        let api_key_references = security_reference_count(&normalized, "apiKey");
        let authorization_references = security_reference_count(&normalized, "Authorization");
        self.observations
            .lock()
            .expect("observations lock should be available")
            .replace(ContractObservations {
                operation_count,
                api_key_references,
                authorization_references,
                responses: operation_responses(&normalized),
            });

        FixtureGenerator {
            operations: operation_count,
        }
        .generate(source, output)
    }
}

struct ContractObservations {
    operation_count: usize,
    api_key_references: usize,
    authorization_references: usize,
    responses: Vec<(String, String, Value)>,
}

fn operations(contract: &Value) -> impl Iterator<Item = (&String, &String, &Value)> {
    contract["paths"]
        .as_object()
        .into_iter()
        .flat_map(|paths| paths.iter())
        .flat_map(|(path, item)| {
            item.as_object().into_iter().flat_map(move |item| {
                item.iter().filter_map(move |(method, operation)| {
                    [
                        "delete", "get", "head", "options", "patch", "post", "put", "trace",
                    ]
                    .contains(&method.as_str())
                    .then_some((path, method, operation))
                })
            })
        })
}

fn operation_count(contract: &Value) -> usize {
    operations(contract).count()
}

fn security_reference_count(contract: &Value, name: &str) -> usize {
    operations(contract)
        .flat_map(|(_, _, operation)| operation["security"].as_array().into_iter().flatten())
        .filter(|requirement| requirement.get(name).is_some())
        .count()
}

fn operation_responses(contract: &Value) -> Vec<(String, String, Value)> {
    operations(contract)
        .map(|(path, method, operation)| {
            (path.clone(), method.clone(), operation["responses"].clone())
        })
        .collect()
}

struct CodegenFixture {
    _directory: TempDir,
    paths: CodegenPaths,
}

impl CodegenFixture {
    fn new(operation_count: usize) -> Self {
        let directory = tempfile::tempdir().expect("temporary directory should exist");
        let source = directory.path().join("dokploy.json");
        let paths = (0..operation_count)
            .map(|index| {
                format!(
                    r#""/fixture.{index}": {{"get": {{"operationId": "fixture-{index}", "security": [{{"Authorization": []}}], "responses": {{"200": {{"description": "ok", "content": {{"application/json": {{"schema": {{"type": "object", "properties": {{}}, "additionalProperties": false}}}}}}}}}}}}}}"#,
                )
            })
            .collect::<Vec<_>>()
            .join(",");
        fs::write(
            &source,
            format!(
                r#"{{"openapi":"3.1.0","info":{{"title":"Fixture","version":"1"}},"security":[{{"apiKey":[]}}],"paths":{{{paths}}},"components":{{"securitySchemes":{{"apiKey":{{"type":"apiKey","in":"header","name":"x-api-key"}}}}}}}}"#,
            ),
        )
        .expect("fixture contract should be written");

        let paths = CodegenPaths {
            source,
            committed_output: directory.path().join("generated"),
            scratch_parent: directory.path().join("scratch"),
            expected_warning_count: 0,
        };

        Self {
            _directory: directory,
            paths,
        }
    }
}
