use std::fs;

use tempfile::TempDir;
use xtask::{CodegenMode, ImperativeCodegenError, ImperativeCodegenPaths, run_imperative_codegen};

#[test]
fn imperative_codegen_emits_clap_commands_and_wire_inputs() {
    let fixture = ImperativeFixture::new();

    let report = run_imperative_codegen(&fixture.paths, CodegenMode::Write)
        .expect("imperative command generation succeeds");
    let source = fs::read_to_string(&fixture.paths.committed_output)
        .expect("generated commands are readable");

    assert_eq!(report.operation_count, 2);
    assert!(source.starts_with("// @generated by `cargo xtask codegen`; DO NOT EDIT."));
    assert!(source.contains("pub enum ApplicationCommand"));
    assert!(source.contains("#[command(name = \"create\")]"));
    assert!(source.contains("long = \"body-environment-id\""));
    assert!(source.contains("required_unless_present = \"body_json\""));
    assert!(source.contains("long = \"query-application-id\""));
    assert!(source.contains("value_parser = [\"docker\", \"github\"]"));
}

#[test]
fn imperative_codegen_check_reports_drift_without_rewriting_it() {
    let fixture = ImperativeFixture::new();
    run_imperative_codegen(&fixture.paths, CodegenMode::Write)
        .expect("initial generation succeeds");
    fs::write(&fixture.paths.committed_output, "manual edit\n")
        .expect("generated file can be changed for the fixture");

    let error = run_imperative_codegen(&fixture.paths, CodegenMode::Check)
        .expect_err("drift must fail check mode");

    assert!(
        matches!(error, ImperativeCodegenError::Drift(path) if path == fixture.paths.committed_output)
    );
    assert_eq!(
        fs::read_to_string(&fixture.paths.committed_output).expect("drifted file is readable"),
        "manual edit\n"
    );
}

#[test]
fn imperative_codegen_covers_every_operation_in_the_vendored_contract() {
    let directory = tempfile::tempdir().expect("temporary directory exists");
    let repository_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask remains directly below the repository root");
    let paths = ImperativeCodegenPaths {
        source: repository_root.join("openapi/dokploy.json"),
        committed_output: directory.path().join("imperative_generated.rs"),
        scratch_parent: directory.path().join("scratch"),
    };

    let report = run_imperative_codegen(&paths, CodegenMode::Write)
        .expect("the full imperative command catalog generates");

    assert_eq!(report.operation_count, 604);
    assert_eq!(report.resource_count, 57);
    assert_eq!(report.input_count, 2_055);
}

struct ImperativeFixture {
    _directory: TempDir,
    paths: ImperativeCodegenPaths,
}

impl ImperativeFixture {
    fn new() -> Self {
        let directory = tempfile::tempdir().expect("temporary directory exists");
        let source = directory.path().join("dokploy.json");
        fs::write(
            &source,
            r#"{
  "openapi": "3.1.0",
  "info": {"title": "Fixture", "version": "1"},
  "paths": {
    "/application.create": {
      "post": {
        "operationId": "application-create",
        "tags": ["application"],
        "requestBody": {"content": {"application/json": {"schema": {
          "type": "object",
          "properties": {
            "name": {"type": "string"},
            "environmentId": {"type": "string"},
            "sourceType": {"type": "string", "enum": ["github", "docker"]}
          },
          "required": ["name", "environmentId"]
        }}}},
        "responses": {"200": {"description": "ok"}}
      }
    },
    "/application.one": {
      "get": {
        "operationId": "application-one",
        "tags": ["application"],
        "parameters": [{"in": "query", "name": "applicationId", "required": true, "schema": {"type": "string"}}],
        "responses": {"200": {"description": "ok"}}
      }
    }
  }
}"#,
        )
        .expect("fixture contract is writable");

        let paths = ImperativeCodegenPaths {
            source,
            committed_output: directory.path().join("imperative_generated.rs"),
            scratch_parent: directory.path().join("scratch"),
        };

        Self {
            _directory: directory,
            paths,
        }
    }
}
