use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::{Map, Value};
use thiserror::Error;

use crate::CodegenMode;

const GENERATED_HEADER: &str = "// @generated by `cargo xtask codegen`; DO NOT EDIT.\n";
const HTTP_METHODS: [&str; 2] = ["get", "post"];

#[derive(Debug, Clone)]
pub struct ImperativeCodegenPaths {
    pub source: PathBuf,
    pub committed_output: PathBuf,
    pub scratch_parent: PathBuf,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ImperativeCodegenReport {
    pub operation_count: usize,
    pub resource_count: usize,
    pub input_count: usize,
}

#[derive(Debug, Error)]
pub enum ImperativeCodegenError {
    #[error("failed to read OpenAPI contract at {path}: {source}")]
    ReadContract {
        path: PathBuf,
        source: std::io::Error,
    },

    #[error("OpenAPI contract at {path} is not valid JSON: {source}")]
    ParseContract {
        path: PathBuf,
        source: serde_json::Error,
    },

    #[error("cannot generate imperative command catalog: {0}")]
    InvalidContract(String),

    #[error("failed to prepare imperative code-generation scratch directory at {path}: {source}")]
    Scratch {
        path: PathBuf,
        source: std::io::Error,
    },

    #[error("rustfmt failed for generated imperative commands: {0}")]
    Format(String),

    #[error("failed to read generated imperative commands at {path}: {source}")]
    ReadGenerated {
        path: PathBuf,
        source: std::io::Error,
    },

    #[error("failed to write generated imperative commands at {path}: {source}")]
    WriteGenerated {
        path: PathBuf,
        source: std::io::Error,
    },

    #[error("generated imperative commands are stale: {}", .0.display())]
    Drift(PathBuf),
}

pub fn run_imperative_codegen(
    paths: &ImperativeCodegenPaths,
    mode: CodegenMode,
) -> Result<ImperativeCodegenReport, ImperativeCodegenError> {
    let bytes = fs::read(&paths.source).map_err(|source| ImperativeCodegenError::ReadContract {
        path: paths.source.clone(),
        source,
    })?;
    let contract: Value =
        serde_json::from_slice(&bytes).map_err(|source| ImperativeCodegenError::ParseContract {
            path: paths.source.clone(),
            source,
        })?;
    let operations = read_operations(&contract)?;
    let report = ImperativeCodegenReport {
        operation_count: operations.len(),
        resource_count: operations
            .iter()
            .map(|operation| operation.resource.as_str())
            .collect::<BTreeSet<_>>()
            .len(),
        input_count: operations
            .iter()
            .map(|operation| {
                operation.query.len() + operation.body.as_ref().map_or(0, |body| body.inputs.len())
            })
            .sum(),
    };
    if report.operation_count == 0 {
        return Err(ImperativeCodegenError::InvalidContract(
            "the contract does not declare any GET or POST operations".to_owned(),
        ));
    }

    let source = format_generated_source(&operations);
    let formatted = format_rust(paths, &source)?;

    match mode {
        CodegenMode::Write => write_generated(&paths.committed_output, &formatted)?,
        CodegenMode::Check => check_generated(&paths.committed_output, &formatted)?,
    }

    Ok(report)
}

#[derive(Debug)]
struct Operation {
    resource: String,
    command: String,
    operation_id: String,
    path: String,
    method: Method,
    query: Vec<Input>,
    body: Option<Body>,
}

#[derive(Debug, Clone, Copy)]
enum Method {
    Get,
    Post,
}

#[derive(Debug)]
struct Body {
    kind: BodyKind,
    inputs: Vec<Input>,
}

#[derive(Debug, Clone, Copy)]
enum BodyKind {
    Json,
    Multipart,
}

#[derive(Debug)]
struct Input {
    wire_name: String,
    cli_name: String,
    field_name: String,
    kind: InputKind,
    required: bool,
    nullable: bool,
    enum_values: Vec<String>,
}

#[derive(Debug, Clone, Copy)]
enum InputKind {
    String,
    Number,
    Integer,
    Boolean,
    Array,
    Object,
    Json,
    File,
}

fn read_operations(contract: &Value) -> Result<Vec<Operation>, ImperativeCodegenError> {
    let paths = contract
        .get("paths")
        .and_then(Value::as_object)
        .ok_or_else(|| invalid("the contract does not contain a paths object"))?;
    let mut operations = Vec::new();
    let mut command_keys = BTreeSet::new();

    for (path, item) in paths {
        let item = item
            .as_object()
            .ok_or_else(|| invalid(format!("path {path} is not an object")))?;
        for method in HTTP_METHODS {
            let Some(operation) = item.get(method).and_then(Value::as_object) else {
                continue;
            };
            let operation_id = required_string(operation, "operationId", path)?;
            let path_name = path.trim_start_matches('/');
            let (resource_name, command_name) = path_name.split_once('.').ok_or_else(|| {
                invalid(format!(
                    "operation {operation_id} path {path} has no resource separator"
                ))
            })?;
            let resource = to_kebab_case(resource_name);
            let command = to_kebab_case(command_name);
            if resource.is_empty() || command.is_empty() {
                return Err(invalid(format!(
                    "operation {operation_id} does not produce a valid command name"
                )));
            }
            if !command_keys.insert((resource.clone(), command.clone())) {
                return Err(invalid(format!(
                    "multiple operations map to `{resource} {command}`"
                )));
            }

            let query = read_query_inputs(operation, operation_id)?;
            let body = read_body(operation, operation_id)?;
            operations.push(Operation {
                resource,
                command,
                operation_id: operation_id.to_owned(),
                path: path_name.to_owned(),
                method: match method {
                    "get" => Method::Get,
                    "post" => Method::Post,
                    _ => unreachable!("HTTP method allowlist is exhaustive"),
                },
                query,
                body,
            });
        }
    }

    operations.sort_by(|left, right| {
        (&left.resource, &left.command).cmp(&(&right.resource, &right.command))
    });

    Ok(operations)
}

fn required_string<'a>(
    object: &'a Map<String, Value>,
    key: &str,
    path: &str,
) -> Result<&'a str, ImperativeCodegenError> {
    object.get(key).and_then(Value::as_str).ok_or_else(|| {
        invalid(format!(
            "operation at {path} does not define a string {key}"
        ))
    })
}

fn read_query_inputs(
    operation: &Map<String, Value>,
    operation_id: &str,
) -> Result<Vec<Input>, ImperativeCodegenError> {
    operation
        .get("parameters")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter(|parameter| parameter.get("in").and_then(Value::as_str) == Some("query"))
        .map(|parameter| {
            let wire_name = parameter
                .get("name")
                .and_then(Value::as_str)
                .ok_or_else(|| {
                    invalid(format!(
                        "{operation_id} has a query parameter without a name"
                    ))
                })?;
            let schema = parameter
                .get("schema")
                .and_then(Value::as_object)
                .ok_or_else(|| {
                    invalid(format!("{operation_id} query {wire_name} has no schema"))
                })?;

            input_from_schema(
                wire_name,
                &format!("query-{}", to_kebab_case(wire_name)),
                &format!("query_{}", to_snake_case(wire_name)),
                schema,
                parameter
                    .get("required")
                    .and_then(Value::as_bool)
                    .unwrap_or(false),
            )
        })
        .collect()
}

fn read_body(
    operation: &Map<String, Value>,
    operation_id: &str,
) -> Result<Option<Body>, ImperativeCodegenError> {
    let Some(content) = operation
        .get("requestBody")
        .and_then(|request_body| request_body.get("content"))
        .and_then(Value::as_object)
    else {
        return Ok(None);
    };
    let (kind, media) = if let Some(media) = content.get("application/json") {
        (BodyKind::Json, media)
    } else if let Some(media) = content.get("multipart/form-data") {
        (BodyKind::Multipart, media)
    } else {
        return Err(invalid(format!(
            "{operation_id} uses an unsupported request body media type"
        )));
    };
    let schema = media
        .get("schema")
        .and_then(Value::as_object)
        .ok_or_else(|| invalid(format!("{operation_id} request body has no object schema")))?;
    if schema.get("type").and_then(Value::as_str) != Some("object") {
        return Err(invalid(format!(
            "{operation_id} request body is not an object"
        )));
    }
    let required = schema
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .ok_or_else(|| invalid(format!("{operation_id} body does not define properties")))?;
    let mut inputs = Vec::with_capacity(properties.len());
    let mut cli_names = BTreeSet::new();
    for (wire_name, schema) in properties {
        let schema = schema.as_object().ok_or_else(|| {
            invalid(format!(
                "{operation_id} body field {wire_name} has no schema"
            ))
        })?;
        let cli_name = format!("body-{}", to_kebab_case(wire_name));
        if !cli_names.insert(cli_name.clone()) {
            return Err(invalid(format!(
                "{operation_id} contains colliding body field names"
            )));
        }
        inputs.push(input_from_schema(
            wire_name,
            &cli_name,
            &format!("body_{}", to_snake_case(wire_name)),
            schema,
            required.iter().any(|name| *name == wire_name),
        )?);
    }

    Ok(Some(Body { kind, inputs }))
}

fn input_from_schema(
    wire_name: &str,
    cli_name: &str,
    field_name: &str,
    schema: &Map<String, Value>,
    required: bool,
) -> Result<Input, ImperativeCodegenError> {
    let nullable = schema
        .get("anyOf")
        .and_then(Value::as_array)
        .is_some_and(|variants| {
            variants
                .iter()
                .any(|variant| variant.get("type").and_then(Value::as_str) == Some("null"))
        });
    let kind = if schema.get("format").and_then(Value::as_str) == Some("binary") {
        InputKind::File
    } else {
        let mut types = schema
            .get("type")
            .and_then(Value::as_str)
            .into_iter()
            .chain(
                schema
                    .get("anyOf")
                    .and_then(Value::as_array)
                    .into_iter()
                    .flatten()
                    .filter_map(|variant| variant.get("type").and_then(Value::as_str)),
            )
            .filter(|kind| *kind != "null")
            .collect::<BTreeSet<_>>();
        if types.len() != 1 {
            InputKind::Json
        } else {
            match types
                .pop_first()
                .expect("one schema type was checked above")
            {
                "string" => InputKind::String,
                "number" => InputKind::Number,
                "integer" => InputKind::Integer,
                "boolean" => InputKind::Boolean,
                "array" => InputKind::Array,
                "object" => InputKind::Object,
                other => {
                    return Err(invalid(format!(
                        "input {wire_name} uses unsupported schema type {other}"
                    )));
                }
            }
        }
    };
    let mut enum_values = schema
        .get("enum")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .chain(
            schema
                .get("anyOf")
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
                .filter_map(|variant| variant.get("enum").and_then(Value::as_array))
                .flatten()
                .filter_map(Value::as_str),
        )
        .map(str::to_owned)
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect::<Vec<_>>();
    if nullable && !enum_values.is_empty() {
        enum_values.push("null".to_owned());
    }

    Ok(Input {
        wire_name: wire_name.to_owned(),
        cli_name: cli_name.to_owned(),
        field_name: rust_field_name(field_name),
        kind,
        required,
        nullable,
        enum_values,
    })
}

fn format_generated_source(operations: &[Operation]) -> String {
    let mut source = String::from(GENERATED_HEADER);
    source.push_str(
        "#![allow(clippy::enum_variant_names)]\n\nuse clap::{Args, Subcommand};\n\nuse crate::imperative::{BodyKind, InputKind, InputSpec, ImperativeInputError, ImperativeInvocation, OperationMethod, OperationSpec, build_invocation};\n\n",
    );
    source.push_str("pub(crate) static OPERATIONS: &[OperationSpec] = &[\n");
    for operation in operations {
        write_operation_spec(&mut source, operation);
    }
    source.push_str("];\n\n");

    let grouped = group_operations(operations);
    source.push_str("#[derive(Subcommand)]\npub enum ImperativeCommand {\n");
    for resource in grouped.keys() {
        let variant = to_pascal_case(resource);
        source.push_str(&format!(
            "    #[command(name = {resource:?})]\n    {variant} {{\n        #[command(subcommand)]\n        command: Box<{variant}Command>,\n    }},\n"
        ));
    }
    source.push_str("}\n\n");
    source.push_str(
        "impl ImperativeCommand {\n    pub fn into_invocation(self) -> Result<ImperativeInvocation, ImperativeInputError> {\n        match self {\n",
    );
    for resource in grouped.keys() {
        let variant = to_pascal_case(resource);
        source.push_str(&format!(
            "            Self::{variant} {{ command }} => command.into_invocation(),\n"
        ));
    }
    source.push_str("        }\n    }\n}\n\n");

    for (resource, indices) in &grouped {
        write_resource_commands(&mut source, resource, indices, operations);
    }

    source
}

fn group_operations(operations: &[Operation]) -> BTreeMap<&str, Vec<usize>> {
    let mut grouped = BTreeMap::<&str, Vec<usize>>::new();
    for (index, operation) in operations.iter().enumerate() {
        grouped.entry(&operation.resource).or_default().push(index);
    }
    grouped
}

fn write_operation_spec(source: &mut String, operation: &Operation) {
    source.push_str("    OperationSpec {\n");
    source.push_str(&format!("        resource: {:?},\n", operation.resource));
    source.push_str(&format!("        command: {:?},\n", operation.command));
    source.push_str(&format!(
        "        operation_id: {:?},\n",
        operation.operation_id
    ));
    source.push_str(&format!("        path: {:?},\n", operation.path));
    source.push_str(&format!(
        "        method: OperationMethod::{:?},\n",
        operation.method
    ));
    source.push_str("        query: &[\n");
    for input in &operation.query {
        write_input_spec(source, input);
    }
    source.push_str("        ],\n");
    match &operation.body {
        Some(body) => {
            source.push_str(&format!(
                "        body_kind: Some(BodyKind::{:?}),\n",
                body.kind
            ));
            source.push_str("        body: &[\n");
            for input in &body.inputs {
                write_input_spec(source, input);
            }
            source.push_str("        ],\n");
        }
        None => source.push_str("        body_kind: None,\n        body: &[],\n"),
    }
    source.push_str("    },\n");
}

fn write_input_spec(source: &mut String, input: &Input) {
    source.push_str(&format!(
        "            InputSpec {{ wire_name: {:?}, cli_name: {:?}, kind: InputKind::{:?}, required: {}, nullable: {}, enum_values: &{:?} }},\n",
        input.wire_name,
        input.cli_name,
        input.kind,
        input.required,
        input.nullable,
        input.enum_values
    ));
}

fn write_resource_commands(
    source: &mut String,
    resource: &str,
    indices: &[usize],
    operations: &[Operation],
) {
    let resource_type = to_pascal_case(resource);
    source.push_str(&format!(
        "#[derive(Subcommand)]\npub enum {resource_type}Command {{\n"
    ));
    for index in indices {
        let operation = &operations[*index];
        let variant = to_pascal_case(&operation.command);
        let args_type = operation_args_type(operation);
        source.push_str(&format!("    #[command(name = {:?})]\n", operation.command));
        if operation.query.is_empty() && operation.body.is_none() {
            source.push_str(&format!("    {variant},\n"));
        } else {
            source.push_str(&format!("    {variant}(Box<{args_type}>),\n"));
        }
    }
    source.push_str("}\n\n");
    source.push_str(&format!(
        "impl {resource_type}Command {{\n    fn into_invocation(self) -> Result<ImperativeInvocation, ImperativeInputError> {{\n        match self {{\n"
    ));
    for index in indices {
        let operation = &operations[*index];
        let variant = to_pascal_case(&operation.command);
        if operation.query.is_empty() && operation.body.is_none() {
            source.push_str(&format!(
                "            Self::{variant} => build_invocation(&OPERATIONS[{index}], None, vec![], vec![]),\n"
            ));
        } else {
            let query = operation
                .query
                .iter()
                .map(|input| format!("({:?}, args.{})", input.wire_name, input.field_name))
                .collect::<Vec<_>>()
                .join(", ");
            let body = operation
                .body
                .as_ref()
                .into_iter()
                .flat_map(|body| &body.inputs)
                .map(|input| format!("({:?}, args.{})", input.wire_name, input.field_name))
                .collect::<Vec<_>>()
                .join(", ");
            let raw_body = operation
                .body
                .as_ref()
                .and_then(|body| matches!(body.kind, BodyKind::Json).then_some("args.body_json"));
            source.push_str(&format!(
                "            Self::{variant}(args) => build_invocation(&OPERATIONS[{index}], {}, vec![{query}], vec![{body}]),\n",
                raw_body.unwrap_or("None")
            ));
        }
    }
    source.push_str("        }\n    }\n}\n\n");

    for index in indices {
        let operation = &operations[*index];
        if operation.query.is_empty() && operation.body.is_none() {
            continue;
        }
        write_operation_args(source, operation);
    }
}

fn write_operation_args(source: &mut String, operation: &Operation) {
    let args_type = operation_args_type(operation);
    source.push_str(&format!("#[derive(Args)]\npub struct {args_type} {{\n"));
    for input in &operation.query {
        write_arg(source, input, false);
    }
    if let Some(body) = &operation.body {
        if matches!(body.kind, BodyKind::Json) {
            source.push_str(
                "    /// Complete JSON body. Cannot be combined with generated body fields.\n    #[arg(long = \"body-json\", value_name = \"JSON\")]\n    body_json: Option<String>,\n",
            );
        }
        for input in &body.inputs {
            write_arg(source, input, matches!(body.kind, BodyKind::Json));
        }
    }
    source.push_str("}\n\n");
}

fn write_arg(source: &mut String, input: &Input, has_raw_body: bool) {
    let value_name = match input.kind {
        InputKind::String => "STRING",
        InputKind::Number => "NUMBER",
        InputKind::Integer => "INTEGER",
        InputKind::Boolean => "BOOLEAN",
        InputKind::Array => "JSON_ARRAY",
        InputKind::Object => "JSON_OBJECT",
        InputKind::Json => "JSON",
        InputKind::File => "FILE",
    };
    source.push_str(&format!("    /// Wire field `{}`.\n", input.wire_name));
    source.push_str(&format!(
        "    #[arg(long = {:?}, value_name = {value_name:?}",
        input.cli_name
    ));
    if has_raw_body {
        source.push_str(", conflicts_with = \"body_json\"");
        if input.required {
            source.push_str(", required_unless_present = \"body_json\"");
        }
    } else if input.required {
        source.push_str(", required = true");
    }
    if !input.enum_values.is_empty() {
        source.push_str(&format!(", value_parser = {:?}", input.enum_values));
    }
    source.push_str(")]\n");
    source.push_str(&format!("    {}: Option<String>,\n", input.field_name));
}

fn operation_args_type(operation: &Operation) -> String {
    format!(
        "{}{}Args",
        to_pascal_case(&operation.resource),
        to_pascal_case(&operation.command)
    )
}

fn format_rust(
    paths: &ImperativeCodegenPaths,
    source: &str,
) -> Result<Vec<u8>, ImperativeCodegenError> {
    fs::create_dir_all(&paths.scratch_parent).map_err(|source| {
        ImperativeCodegenError::Scratch {
            path: paths.scratch_parent.clone(),
            source,
        }
    })?;
    let scratch = tempfile::Builder::new()
        .prefix("dokploy-cli-")
        .tempdir_in(&paths.scratch_parent)
        .map_err(|source| ImperativeCodegenError::Scratch {
            path: paths.scratch_parent.clone(),
            source,
        })?;
    let path = scratch.path().join("imperative_generated.rs");
    fs::write(&path, source).map_err(|source| ImperativeCodegenError::WriteGenerated {
        path: path.clone(),
        source,
    })?;
    let output = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(&path)
        .output()
        .map_err(|source| ImperativeCodegenError::Format(source.to_string()))?;
    if !output.status.success() {
        return Err(ImperativeCodegenError::Format(
            String::from_utf8_lossy(&output.stderr).into_owned(),
        ));
    }

    fs::read(&path).map_err(|source| ImperativeCodegenError::ReadGenerated { path, source })
}

fn write_generated(path: &Path, contents: &[u8]) -> Result<(), ImperativeCodegenError> {
    let parent = path
        .parent()
        .ok_or_else(|| invalid("generated imperative command path has no parent"))?;
    fs::create_dir_all(parent).map_err(|source| ImperativeCodegenError::WriteGenerated {
        path: parent.to_path_buf(),
        source,
    })?;
    fs::write(path, contents).map_err(|source| ImperativeCodegenError::WriteGenerated {
        path: path.to_path_buf(),
        source,
    })
}

fn check_generated(path: &Path, expected: &[u8]) -> Result<(), ImperativeCodegenError> {
    match fs::read(path) {
        Ok(actual) if actual == expected => Ok(()),
        Ok(_) | Err(_) => Err(ImperativeCodegenError::Drift(path.to_path_buf())),
    }
}

fn invalid(message: impl Into<String>) -> ImperativeCodegenError {
    ImperativeCodegenError::InvalidContract(message.into())
}

fn to_kebab_case(value: &str) -> String {
    split_words(value).join("-")
}

fn to_snake_case(value: &str) -> String {
    split_words(value).join("_")
}

fn to_pascal_case(value: &str) -> String {
    split_words(value)
        .into_iter()
        .map(|word| {
            let mut characters = word.chars();
            let Some(first) = characters.next() else {
                return String::new();
            };
            format!("{}{}", first.to_ascii_uppercase(), characters.as_str())
        })
        .collect()
}

fn split_words(value: &str) -> Vec<String> {
    let characters = value.chars().collect::<Vec<_>>();
    let mut words = Vec::new();
    let mut word = String::new();
    for (index, character) in characters.iter().copied().enumerate() {
        if !character.is_ascii_alphanumeric() {
            if !word.is_empty() {
                words.push(std::mem::take(&mut word));
            }
            continue;
        }
        let previous = index.checked_sub(1).and_then(|index| characters.get(index));
        let next = characters.get(index + 1);
        let starts_word = character.is_ascii_uppercase()
            && !word.is_empty()
            && (previous.is_some_and(|previous| {
                previous.is_ascii_lowercase() || previous.is_ascii_digit()
            }) || next.is_some_and(|next| next.is_ascii_lowercase()));
        if starts_word {
            words.push(std::mem::take(&mut word));
        }
        word.push(character.to_ascii_lowercase());
    }
    if !word.is_empty() {
        words.push(word);
    }
    words
}

fn rust_field_name(value: &str) -> String {
    let mut name = value.to_owned();
    if name.starts_with(|character: char| character.is_ascii_digit()) {
        name.insert(0, '_');
    }
    if [
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
        "use", "where", "while", "async", "await", "dyn",
    ]
    .contains(&name.as_str())
    {
        name.push('_');
    }
    name
}

#[cfg(test)]
mod tests {
    use super::{to_kebab_case, to_pascal_case, to_snake_case};

    #[test]
    fn identifier_cases_preserve_acronym_boundaries() {
        assert_eq!(to_kebab_case("readTraefikConfig"), "read-traefik-config");
        assert_eq!(
            to_kebab_case("deployNginxQuickstart"),
            "deploy-nginx-quickstart"
        );
        assert_eq!(to_snake_case("applicationId"), "application_id");
        assert_eq!(to_pascal_case("dns-provider"), "DnsProvider");
    }
}
