use std::{
    collections::BTreeSet,
    fs, io,
    path::{Path, PathBuf},
    process::Command,
};

use serde_json::Value;
use thiserror::Error;

mod goldens;
mod imperative;
mod specs;
mod versions;

pub use goldens::{GoldensExtractReport, GoldensReport, run_goldens_check, run_goldens_extract};
pub use imperative::{
    ImperativeCodegenError, ImperativeCodegenPaths, ImperativeCodegenReport, run_imperative_codegen,
};
pub use specs::{SpecsReport, run_specs_check};
pub use versions::{VersionsReport, load_versions, run_versions_check, version_image};

pub const GENERATOR_VERSION: &str = "oas3-gen 0.28.0";

const GENERATOR_FILES: [&str; 3] = ["client.rs", "mod.rs", "types.rs"];
const GENERATED_FILES: [&str; 4] = ["client.rs", "metadata.rs", "mod.rs", "types.rs"];
const GENERATED_HEADER: &str = "// @generated by `cargo xtask codegen`; DO NOT EDIT.\n";
const KNOWN_WARNING_PREFIX: &str = "Warning: Invalid regex pattern";
const HTTP_METHODS: [&str; 8] = [
    "delete", "get", "head", "options", "patch", "post", "put", "trace",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodegenMode {
    Write,
    Check,
}

#[derive(Debug, Clone)]
pub struct CodegenPaths {
    pub source: PathBuf,
    pub committed_output: PathBuf,
    pub scratch_parent: PathBuf,
    pub expected_warning_count: usize,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct GeneratorOutput {
    pub stderr: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodegenReport {
    pub operation_count: usize,
    pub file_count: usize,
    pub warning_count: usize,
    pub normalized_security_references: usize,
}

pub trait CodeGenerator {
    fn version(&self) -> Result<String, io::Error>;

    fn generate(&self, source: &Path, output: &Path) -> Result<GeneratorOutput, io::Error>;
}

#[derive(Debug, Error)]
pub enum CodegenError {
    #[error("failed to read OpenAPI contract at {path}: {source}")]
    ReadContract { path: PathBuf, source: io::Error },

    #[error("OpenAPI contract at {path} is not valid JSON: {source}")]
    ParseContract {
        path: PathBuf,
        source: serde_json::Error,
    },

    #[error("OpenAPI contract must declare at least one operationId")]
    EmptyContract,

    #[error("OpenAPI contract does not define the expected `apiKey` security scheme")]
    MissingApiKeySecurityScheme,

    #[error("cannot normalize a security requirement containing both `Authorization` and `apiKey`")]
    ConflictingSecurityReferences,

    #[error("normalizing authentication changed the operation count from {before} to {after}")]
    NormalizationChangedOperationCount { before: usize, after: usize },

    #[error("failed to serialize normalized OpenAPI contract: {0}")]
    SerializeContract(#[source] serde_json::Error),

    #[error("failed to write normalized OpenAPI contract at {path}: {source}")]
    WriteNormalizedContract { path: PathBuf, source: io::Error },

    #[error("expected `{expected}` but found `{actual}`")]
    GeneratorVersion { expected: String, actual: String },

    #[error("failed to execute pinned OpenAPI generator: {0}")]
    Generator(#[source] io::Error),

    #[error("failed to prepare code-generation scratch directory at {path}: {source}")]
    Scratch { path: PathBuf, source: io::Error },

    #[error("generator emitted unexpected diagnostics: {0}")]
    UnexpectedDiagnostics(String),

    #[error("generator emitted {actual} known warnings; expected {expected}")]
    WarningCountMismatch { expected: usize, actual: usize },

    #[error("generator did not create expected file {0}")]
    MissingGeneratedFile(PathBuf),

    #[error("generator emitted no operations for a contract containing {expected} operations")]
    EmptyGeneratedOperations { expected: usize },

    #[error(
        "generator emitted {actual} operations for a contract containing {expected} operations"
    )]
    OperationCountMismatch { expected: usize, actual: usize },

    #[error("generated directory contains unexpected entries: {0:?}")]
    UnexpectedGeneratedFiles(Vec<PathBuf>),

    #[error("failed to read generated file at {path}: {source}")]
    ReadGenerated { path: PathBuf, source: io::Error },

    #[error("failed to write generated file at {path}: {source}")]
    WriteGenerated { path: PathBuf, source: io::Error },

    #[error("cannot derive generated endpoint metadata: {0}")]
    EndpointMetadata(String),

    #[error("failed to format generated endpoint metadata: {0}")]
    FormatEndpointMetadata(String),

    #[error("generated Dokploy bindings are stale: {0:?}")]
    Drift(Vec<PathBuf>),
}

pub fn run_codegen(
    generator: &dyn CodeGenerator,
    paths: &CodegenPaths,
    mode: CodegenMode,
) -> Result<CodegenReport, CodegenError> {
    let mut contract = read_contract(&paths.source)?;
    let expected_operations = contract_operation_count(&contract);
    if expected_operations == 0 {
        return Err(CodegenError::EmptyContract);
    }

    let actual_version = generator.version().map_err(CodegenError::Generator)?;
    if actual_version.trim() != GENERATOR_VERSION {
        return Err(CodegenError::GeneratorVersion {
            expected: GENERATOR_VERSION.to_owned(),
            actual: actual_version.trim().to_owned(),
        });
    }

    fs::create_dir_all(&paths.scratch_parent).map_err(|source| CodegenError::Scratch {
        path: paths.scratch_parent.clone(),
        source,
    })?;
    let scratch = tempfile::Builder::new()
        .prefix("dokploy-api-")
        .tempdir_in(&paths.scratch_parent)
        .map_err(|source| CodegenError::Scratch {
            path: paths.scratch_parent.clone(),
            source,
        })?;
    let normalized_security_references = normalize_security_references(&mut contract)?;
    let normalized_operations = contract_operation_count(&contract);
    if normalized_operations != expected_operations {
        return Err(CodegenError::NormalizationChangedOperationCount {
            before: expected_operations,
            after: normalized_operations,
        });
    }
    let normalized_source = scratch.path().join("openapi/dokploy.json");
    write_normalized_contract(&normalized_source, &contract)?;
    let staged_output = scratch.path().join("generated");
    let generator_output = generator
        .generate(&normalized_source, &staged_output)
        .map_err(CodegenError::Generator)?;
    let warning_count =
        validate_diagnostics(&generator_output.stderr, paths.expected_warning_count)?;
    reject_unexpected_entries(&staged_output, &GENERATOR_FILES)?;
    write_endpoint_metadata(&staged_output, &contract)?;
    let generated = read_generated_files(&staged_output)?;
    let actual_operations = generated_operation_count(&generated)?;

    if actual_operations == 0 {
        return Err(CodegenError::EmptyGeneratedOperations {
            expected: expected_operations,
        });
    }
    if actual_operations != expected_operations {
        return Err(CodegenError::OperationCountMismatch {
            expected: expected_operations,
            actual: actual_operations,
        });
    }

    match mode {
        CodegenMode::Write => write_generated_files(&paths.committed_output, &generated)?,
        CodegenMode::Check => check_generated_files(&paths.committed_output, &generated)?,
    }

    Ok(CodegenReport {
        operation_count: actual_operations,
        file_count: generated.len(),
        warning_count,
        normalized_security_references,
    })
}

fn write_endpoint_metadata(output: &Path, contract: &Value) -> Result<(), CodegenError> {
    let paths = contract
        .get("paths")
        .and_then(Value::as_object)
        .ok_or_else(|| CodegenError::EndpointMetadata("contract has no paths object".to_owned()))?;
    let mut constants = BTreeSet::new();
    let mut endpoints = Vec::new();

    for (path, item) in paths {
        let item = item.as_object().ok_or_else(|| {
            CodegenError::EndpointMetadata(format!("path `{path}` is not an object"))
        })?;

        for method in HTTP_METHODS {
            let Some(operation) = item.get(method) else {
                continue;
            };
            let operation_id = operation
                .get("operationId")
                .and_then(Value::as_str)
                .ok_or_else(|| {
                    CodegenError::EndpointMetadata(format!(
                        "{method} operation at `{path}` has no operationId"
                    ))
                })?;
            let operation_path = path.strip_prefix('/').ok_or_else(|| {
                CodegenError::EndpointMetadata(format!("path `{path}` must begin with `/`"))
            })?;
            if operation_path.is_empty() || operation_path.contains('/') {
                return Err(CodegenError::EndpointMetadata(format!(
                    "path `{path}` is not a single operation segment"
                )));
            }

            let constant = endpoint_constant_name(operation_id);
            if !constants.insert(constant.clone()) {
                return Err(CodegenError::EndpointMetadata(format!(
                    "operationId `{operation_id}` produces duplicate constant `{constant}`"
                )));
            }
            endpoints.push(EndpointDefinition {
                constant,
                method: endpoint_method_variant(method),
                operation_id: operation_id.to_owned(),
                operation: operation_path.to_owned(),
                contract: request_contract_source(operation),
            });
        }
    }

    endpoints.sort_by(|left, right| left.operation.cmp(&right.operation));
    let mut source = String::from(
        "//! Endpoint metadata derived from the pinned OpenAPI contract.\n\nuse crate::{BodyShape, Endpoint, EndpointMethod, RequestContract, RequestField};\n\n",
    );
    for endpoint in &endpoints {
        source.push_str(&format!(
            "pub const {}: Endpoint = Endpoint::new({}, {}, EndpointMethod::{});\n",
            endpoint.constant,
            rust_string(&endpoint.operation_id),
            rust_string(&endpoint.operation),
            endpoint.method,
        ));
    }
    source.push_str("\n/// Looks up endpoint metadata by its Dokploy wire operation.\n#[must_use]\npub fn endpoint_by_operation(operation: &str) -> Option<Endpoint> {\n    match operation {\n");
    for endpoint in &endpoints {
        source.push_str(&format!(
            "        {} => Some({}),\n",
            rust_string(&endpoint.operation),
            endpoint.constant,
        ));
    }
    source.push_str("        _ => None,\n    }\n}\n");
    source.push_str("\n/// Looks up the request fields of an operation by its Dokploy wire operation.\n#[must_use]\npub fn request_contract(operation: &str) -> Option<&'static RequestContract> {\n    match operation {\n");
    for endpoint in &endpoints {
        source.push_str(&format!(
            "        {} => Some(&{}),\n",
            rust_string(&endpoint.operation),
            endpoint.contract,
        ));
    }
    source.push_str("        _ => None,\n    }\n}\n");

    let metadata_path = output.join("metadata.rs");
    fs::write(&metadata_path, source).map_err(|source| CodegenError::WriteGenerated {
        path: metadata_path.clone(),
        source,
    })?;
    let module_path = output.join("mod.rs");
    let mut module =
        fs::read_to_string(&module_path).map_err(|source| CodegenError::ReadGenerated {
            path: module_path.clone(),
            source,
        })?;
    if !module.ends_with('\n') {
        module.push('\n');
    }
    module.push_str("mod metadata;\npub use metadata::*;\n");
    fs::write(&module_path, module).map_err(|source| CodegenError::WriteGenerated {
        path: module_path.clone(),
        source,
    })?;

    let format_output = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(&metadata_path)
        .output()
        .map_err(|error| CodegenError::FormatEndpointMetadata(error.to_string()))?;
    if !format_output.status.success() {
        return Err(CodegenError::FormatEndpointMetadata(
            String::from_utf8_lossy(&format_output.stderr).into_owned(),
        ));
    }

    Ok(())
}

struct EndpointDefinition {
    constant: String,
    method: &'static str,
    operation_id: String,
    operation: String,
    contract: String,
}

/// Rust source for the query parameters and JSON body fields an operation accepts.
///
/// A body that is not a plain object with properties is `Unconstrained`; the contract
/// then says nothing about its fields.
fn request_contract_source(operation: &Value) -> String {
    let mut query = Vec::new();
    for parameter in operation
        .get("parameters")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
    {
        if parameter.get("in").and_then(Value::as_str) != Some("query") {
            continue;
        }
        if let Some(name) = parameter.get("name").and_then(Value::as_str) {
            let required = parameter
                .get("required")
                .and_then(Value::as_bool)
                .unwrap_or(false);
            query.push((name.to_owned(), required));
        }
    }
    query.sort();

    let body = match operation.get("requestBody") {
        None => "BodyShape::None".to_owned(),
        Some(request_body) => {
            let schema = request_body
                .pointer("/content/application~1json/schema")
                .filter(|schema| schema.get("properties").is_some());
            match schema {
                None => "BodyShape::Unconstrained".to_owned(),
                Some(schema) => {
                    let required: BTreeSet<&str> = schema
                        .get("required")
                        .and_then(Value::as_array)
                        .into_iter()
                        .flatten()
                        .filter_map(Value::as_str)
                        .collect();
                    let mut fields: Vec<(String, bool)> = schema
                        .get("properties")
                        .and_then(Value::as_object)
                        .into_iter()
                        .flatten()
                        .map(|(name, _)| (name.clone(), required.contains(name.as_str())))
                        .collect();
                    fields.sort();
                    format!("BodyShape::Object(&[{}])", field_list(&fields))
                }
            }
        }
    };

    format!(
        "RequestContract {{ query: &[{}], body: {body} }}",
        field_list(&query)
    )
}

fn field_list(fields: &[(String, bool)]) -> String {
    fields
        .iter()
        .map(|(name, required)| {
            format!(
                "RequestField {{ name: {}, required: {required} }}",
                rust_string(name)
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn endpoint_constant_name(operation_id: &str) -> String {
    let mut result = String::new();
    let mut previous_is_lower_or_digit = false;

    for character in operation_id.chars() {
        if !character.is_ascii_alphanumeric() {
            if !result.is_empty() && !result.ends_with('_') {
                result.push('_');
            }
            previous_is_lower_or_digit = false;
            continue;
        }
        if character.is_ascii_uppercase() && previous_is_lower_or_digit {
            result.push('_');
        }
        result.push(character.to_ascii_uppercase());
        previous_is_lower_or_digit = character.is_ascii_lowercase() || character.is_ascii_digit();
    }

    if result.starts_with(|character: char| character.is_ascii_digit()) {
        result.insert(0, '_');
    }
    result
}

fn endpoint_method_variant(method: &str) -> &'static str {
    match method {
        "delete" => "Delete",
        "get" => "Get",
        "head" => "Head",
        "options" => "Options",
        "patch" => "Patch",
        "post" => "Post",
        "put" => "Put",
        "trace" => "Trace",
        _ => unreachable!("HTTP method list and variant mapping must stay synchronized"),
    }
}

fn rust_string(value: &str) -> String {
    serde_json::to_string(value).expect("serializing a string cannot fail")
}

fn read_contract(source: &Path) -> Result<Value, CodegenError> {
    let bytes = fs::read(source).map_err(|error| CodegenError::ReadContract {
        path: source.to_path_buf(),
        source: error,
    })?;
    let contract: Value =
        serde_json::from_slice(&bytes).map_err(|error| CodegenError::ParseContract {
            path: source.to_path_buf(),
            source: error,
        })?;

    Ok(contract)
}

fn contract_operation_count(contract: &Value) -> usize {
    contract
        .get("paths")
        .and_then(Value::as_object)
        .into_iter()
        .flat_map(|paths| paths.values())
        .filter_map(Value::as_object)
        .flat_map(|path| {
            HTTP_METHODS
                .iter()
                .filter_map(move |method| path.get(*method))
        })
        .filter(|operation| {
            operation
                .get("operationId")
                .and_then(Value::as_str)
                .is_some()
        })
        .count()
}

fn normalize_security_references(contract: &mut Value) -> Result<usize, CodegenError> {
    let schemes = contract
        .pointer("/components/securitySchemes")
        .and_then(Value::as_object)
        .ok_or(CodegenError::MissingApiKeySecurityScheme)?;
    if !schemes.contains_key("apiKey") {
        return Err(CodegenError::MissingApiKeySecurityScheme);
    }
    if schemes.contains_key("Authorization") {
        return Ok(0);
    }

    let Some(paths) = contract.get_mut("paths").and_then(Value::as_object_mut) else {
        return Ok(0);
    };
    let mut normalized = 0;
    for path in paths.values_mut().filter_map(Value::as_object_mut) {
        for method in HTTP_METHODS {
            let Some(operation) = path.get_mut(method).and_then(Value::as_object_mut) else {
                continue;
            };
            let Some(requirements) = operation.get_mut("security").and_then(Value::as_array_mut)
            else {
                continue;
            };
            for requirement in requirements.iter_mut().filter_map(Value::as_object_mut) {
                if !requirement.contains_key("Authorization") {
                    continue;
                }
                if requirement.contains_key("apiKey") {
                    return Err(CodegenError::ConflictingSecurityReferences);
                }

                let scopes = requirement
                    .remove("Authorization")
                    .expect("security requirement was checked above");
                requirement.insert("apiKey".to_owned(), scopes);
                normalized += 1;
            }
        }
    }

    Ok(normalized)
}

fn write_normalized_contract(path: &Path, contract: &Value) -> Result<(), CodegenError> {
    let parent = path
        .parent()
        .expect("normalized contract path always has a parent directory");
    fs::create_dir_all(parent).map_err(|source| CodegenError::WriteNormalizedContract {
        path: path.to_path_buf(),
        source,
    })?;
    let mut bytes = serde_json::to_vec_pretty(contract).map_err(CodegenError::SerializeContract)?;
    bytes.push(b'\n');
    fs::write(path, bytes).map_err(|source| CodegenError::WriteNormalizedContract {
        path: path.to_path_buf(),
        source,
    })
}

fn validate_diagnostics(
    stderr: &str,
    expected_warning_count: usize,
) -> Result<usize, CodegenError> {
    let diagnostics = stderr
        .lines()
        .filter(|line| !line.trim().is_empty())
        .collect::<Vec<_>>();
    let unexpected = diagnostics
        .iter()
        .copied()
        .filter(|line| !line.starts_with(KNOWN_WARNING_PREFIX))
        .collect::<Vec<_>>();

    if !unexpected.is_empty() {
        return Err(CodegenError::UnexpectedDiagnostics(unexpected.join("\n")));
    }
    if diagnostics.len() != expected_warning_count {
        return Err(CodegenError::WarningCountMismatch {
            expected: expected_warning_count,
            actual: diagnostics.len(),
        });
    }

    Ok(diagnostics.len())
}

fn read_generated_files(output: &Path) -> Result<Vec<(PathBuf, Vec<u8>)>, CodegenError> {
    let mut files = Vec::with_capacity(GENERATED_FILES.len());
    for file_name in GENERATED_FILES {
        let path = output.join(file_name);
        let contents = fs::read(&path).map_err(|source| {
            if source.kind() == io::ErrorKind::NotFound {
                CodegenError::MissingGeneratedFile(path.clone())
            } else {
                CodegenError::ReadGenerated {
                    path: path.clone(),
                    source,
                }
            }
        })?;
        let mut with_header = GENERATED_HEADER.as_bytes().to_vec();
        with_header.extend(contents);
        files.push((PathBuf::from(file_name), with_header));
    }

    reject_unexpected_entries(output, &GENERATED_FILES)?;

    Ok(files)
}

fn generated_operation_count(generated: &[(PathBuf, Vec<u8>)]) -> Result<usize, CodegenError> {
    let (path, contents) = generated
        .iter()
        .find(|(path, _)| path == Path::new("client.rs"))
        .expect("generated file set always contains client.rs");
    let source = std::str::from_utf8(contents).map_err(|error| {
        CodegenError::UnexpectedDiagnostics(format!("{} is not UTF-8: {error}", path.display()))
    })?;

    Ok(source.matches("/// * Path: `").count())
}

fn write_generated_files(
    output: &Path,
    generated: &[(PathBuf, Vec<u8>)],
) -> Result<(), CodegenError> {
    fs::create_dir_all(output).map_err(|source| CodegenError::WriteGenerated {
        path: output.to_path_buf(),
        source,
    })?;
    reject_unexpected_entries(output, &GENERATED_FILES)?;

    for (relative_path, contents) in generated {
        let path = output.join(relative_path);
        fs::write(&path, contents)
            .map_err(|source| CodegenError::WriteGenerated { path, source })?;
    }

    Ok(())
}

fn check_generated_files(
    output: &Path,
    generated: &[(PathBuf, Vec<u8>)],
) -> Result<(), CodegenError> {
    let mut drift = Vec::new();

    for (relative_path, expected) in generated {
        let path = output.join(relative_path);
        match fs::read(&path) {
            Ok(actual) if actual == *expected => {}
            Ok(_) | Err(_) => drift.push(path),
        }
    }

    match reject_unexpected_entries(output, &GENERATED_FILES) {
        Ok(()) => {}
        Err(CodegenError::UnexpectedGeneratedFiles(paths)) => drift.extend(paths),
        Err(error) => return Err(error),
    }

    if drift.is_empty() {
        Ok(())
    } else {
        Err(CodegenError::Drift(drift))
    }
}

fn reject_unexpected_entries(output: &Path, expected: &[&str]) -> Result<(), CodegenError> {
    if !output.exists() {
        return Ok(());
    }

    let expected = expected.iter().map(PathBuf::from).collect::<BTreeSet<_>>();
    let entries = fs::read_dir(output).map_err(|source| CodegenError::ReadGenerated {
        path: output.to_path_buf(),
        source,
    })?;
    let mut unexpected = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|source| CodegenError::ReadGenerated {
            path: output.to_path_buf(),
            source,
        })?;
        let relative = PathBuf::from(entry.file_name());
        if !expected.contains(&relative) {
            unexpected.push(entry.path());
        }
    }

    if unexpected.is_empty() {
        Ok(())
    } else {
        Err(CodegenError::UnexpectedGeneratedFiles(unexpected))
    }
}

#[derive(Debug, Clone)]
pub struct ProcessGenerator {
    executable: PathBuf,
    repository_root: PathBuf,
}

impl ProcessGenerator {
    #[must_use]
    pub fn new(executable: impl Into<PathBuf>, repository_root: impl Into<PathBuf>) -> Self {
        Self {
            executable: executable.into(),
            repository_root: repository_root.into(),
        }
    }
}

impl CodeGenerator for ProcessGenerator {
    fn version(&self) -> Result<String, io::Error> {
        let output = Command::new(&self.executable).arg("--version").output()?;
        if !output.status.success() {
            return Err(io::Error::other(
                String::from_utf8_lossy(&output.stderr).into_owned(),
            ));
        }

        Ok(String::from_utf8_lossy(&output.stdout).into_owned())
    }

    fn generate(&self, source: &Path, output: &Path) -> Result<GeneratorOutput, io::Error> {
        let source_root = source.parent().and_then(Path::parent).ok_or_else(|| {
            io::Error::other("normalized source must be stored below an openapi directory")
        })?;
        let source_argument = source.strip_prefix(source_root).map_err(io::Error::other)?;
        let command_output = Command::new(&self.executable)
            .current_dir(source_root)
            .args(["--color", "never", "generate", "client-mod", "-i"])
            .arg(source_argument)
            .arg("-o")
            .arg(output)
            .arg("--quiet")
            .output()?;
        if !command_output.status.success() {
            return Err(io::Error::other(
                String::from_utf8_lossy(&command_output.stderr).into_owned(),
            ));
        }

        let format_output = Command::new("rustfmt")
            .current_dir(&self.repository_root)
            .args(["--edition", "2024"])
            .arg(output.join("client.rs"))
            .arg(output.join("mod.rs"))
            .arg(output.join("types.rs"))
            .output()?;
        if !format_output.status.success() {
            return Err(io::Error::other(format!(
                "rustfmt failed for generated bindings: {}",
                String::from_utf8_lossy(&format_output.stderr)
            )));
        }

        Ok(GeneratorOutput {
            stderr: String::from_utf8_lossy(&command_output.stderr).into_owned(),
        })
    }
}

#[must_use]
pub fn repository_paths(repository_root: &Path) -> CodegenPaths {
    CodegenPaths {
        source: repository_root.join("openapi/dokploy.json"),
        committed_output: repository_root.join("crates/dokploy-api/src/generated"),
        scratch_parent: repository_root.join("target/codegen"),
        expected_warning_count: 25,
    }
}

#[must_use]
pub fn repository_imperative_paths(repository_root: &Path) -> ImperativeCodegenPaths {
    ImperativeCodegenPaths {
        source: repository_root.join("openapi/dokploy.json"),
        committed_output: repository_root.join("crates/dokploy-cli/src/imperative_generated.rs"),
        scratch_parent: repository_root.join("target/codegen"),
    }
}

#[must_use]
pub fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask must remain directly below the repository root")
        .to_path_buf()
}
